# .github/workflows/ci.yaml
name: CI for Airflow MLOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t custom-airflow-with-dvc .

      - name: Run DVC dry-run
        run: |
          pip install dvc
          dvc doctor
          dvc status || true
